project:
  type: website
  output-dir: docs
  resources:
    - files/

website:
  title: ""
  page-footer: 
    border: true
    left: "© 2025 ICPMF Executive Board"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/company/icpmf
      - icon: facebook
        href: https://www.facebook.com/icpmf11/
      - icon: envelope
        href: mailto:icpmfood@gmail.com
        
  navbar:
    logo: images/logo.png   # <- place this inside the navbar block
    pinned: true   # This makes the navbar fixed on scroll
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd  
      - text: "Events"
        href: events.qmd
      - text: "Board"
        href: members.qmd
      - text: "yICPMF"
        href: young-members.qmd
      - text: "Tools"
        href: tools.qmd
      - text: "Resources"
        menu:
          - text: "Training Material"
            href: training.qmd
          - text: "Webinars"
            href: webinars.qmd
          - text: "ICPMF"
            href: icpmf.qmd
            
      - text: "News"
        href: news.qmd        
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cerulean
    css: [styles.css]
